name: Run tests
on:
  push:
    branches:
    # Only mainline branches, features etc are covered on the pull_request trigger
    - '*.x'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        php_version:
        - '8.2'
        - '8.3'
        - '8.4'
        dependency-versions:
        - 'default'
        - 'lowest'

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        tools: composer:v2

    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Install composer dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: ${{ matrix.dependency-versions }}

    - name: Run koharness
      run: |
        vendor/bin/koharness

    - name: Run unit tests
      run: |
        vendor/bin/phpunit


  coding-standard:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          ini-values: "zend.exception_ignore_args=Off"
          coverage: none

      - name: Install dependencies
        run: composer update

      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff
